/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Jonas Prunskus (https://sketchfab.com/JPrun)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flamethrower-drone-6bc6e70b2c6b467d95f4d7e1756e116f
Title: Flamethrower Drone
*/
// [-0.378, 0, 0]  

import React, { forwardRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';

const Drone = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('/flamethrower_drone.glb');
  const { onLoad } = props
  // Call onLoad when nodes are available
  useEffect(() => {
    if (nodes) {
      onLoad(); // Notify that the drone model has loaded
    }
  }, [nodes, onLoad]);

  return (
    <group ref={ref} dispose={null} scale={[0.3, 0.3, 0.3]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, -0.604, 1.819]} rotation={[-0.378, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Body_0.geometry}
            material={materials.Body}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Body_0_1.geometry}
            material={materials.Body}
          />
        </group>
      </group>
    </group>
  );
});

useGLTF.preload('/flamethrower_drone.glb');

export default Drone;
